### devolve a lista de contas de usuários
GET http://localhost:4000/users

### Buscar os clientes cadastrados (Logado)
GET http://localhost:4000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NzkxMDM0MTQsImV4cCI6MTc3OTEzMjIxNH0.BM85Z6vmt6TUBHmrun0JULM1uXa3hSKzeFLQvfZxD9s

### cadastra uma nova conta de usuário
POST http://localhost:4000/signup HTTP/1.1
content-type: application/json

{
    "name": "user",
    "email": "user@gmail.com",
    "password": "password"
}

### cadastra um novo cliente na conta
POST http://localhost:4000/customers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NzkxMDM3ODIsImV4cCI6MTc3OTEzMjU4Mn0.fGJAfjJu2c8vOMPuqa0Nb1xxxfCUH7ZDgfFt7mv41KM
content-type: application/json

{
    "name": "user",
    "email": "user@gmail.com",
    "phone": "phone",
    "address": "address"
}

### login
POST http://localhost:4000/login HTTP/1.1
content-type: application/json

{
    "email": "carlos.oliveira.dev.junior@gmail.com",
    "password": "123456"
}

### ainda não configurado aqui
PUT http://localhost:4000/usuarios/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Dev Atualizado",
    "email": "novoemail@exemplo.com"
}

### deleta uma conta de usuário pelo id
DELETE http://localhost:4000/users/2
